In [1]:
#Importing all necessary libraries
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("/content/insurance_data.csv")
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               27 non-null     int64
 1   bought_insurance  27 non-null     int64
dtypes: int64(2)
memory usage: 560.0 bytes


In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(df[['age' , 'bought_insurance']] , df.bought_insurance , test_size = 0.2 , random_state = 25)

In [6]:
X_train

age  bought_insurance
0    22                 0
13   29                 0
6    55                 0
17   58                 1
24   50                 1
19   18                 0
25   54                 1
16   25                 1
20   21                 0
3    52                 0
7    60                 1
1    25                 0
5    56                 1
26   23                 0
8    62                 1
18   19                 0
12   27                 0
23   45                 1
22   40                 1
15   55                 1
4    46                 1

In [7]:
len(X_train)

21

## Scaling

In [8]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [10]:
model = keras.Sequential([
    keras.layers.Dense(1 , input_shape = (2,) , activation = 'sigmoid' , kernel_initializer = 'ones' , bias_initializer = 'zeros')
])

model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

model.fit(X_train_scaled , y_train , epochs = 500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5238 - loss: 0.5111
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5238 - loss: 0.5108
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 0.5238 - loss: 0.5105
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.5238 - loss: 0.5102
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - accuracy: 0.5238 - loss: 0.5099
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5238 - loss: 0.5096
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.5238 - loss: 0.5093
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5238 - loss: 0.5090
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step - accuracy: 0.5238 - loss: 0.5087
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.5238 - loss: 0.5084
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.5238 - loss: 0.5081
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.523

In [11]:
model.evaluate(X_test_scaled , y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step - accuracy: 1.0000 - loss: 0.3897


[0.38966765999794006, 1.0]

In [12]:
X_test_scaled

age  bought_insurance
2   0.47                 1
10  0.18                 0
21  0.26                 0
11  0.28                 0
14  0.49                 1
9   0.61                 1

In [13]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[0.7963685 ],
       [0.41857827],
       [0.43077648],
       [0.43383983],
       [0.79838514],
       [0.81017154]], dtype=float32)

In [14]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [24]:
coef , intercept = model.get_weights()
coef , intercept


(array([[0.6241079],
        [1.5113713]], dtype=float32),
 array([-0.44095188], dtype=float32))

## Implementing using python

In [17]:
def sigmoid(x):
  import math
  return 1/(1+math.exp(-x))

In [18]:
sigmoid(18)

0.9999999847700205

In [31]:
def prediction_function(age , bought_insurance):
  weighted_sum = coef[0]*age + coef[1]* bought_insurance + intercept
  return sigmoid(weighted_sum)

In [32]:
prediction_function(0.47 , 1)

<ipython-input-17-b240e5bc802f>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.7963684919475119

In [33]:
prediction_function(.18 , 1)

<ipython-input-17-b240e5bc802f>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.7654434821829318

In [35]:
def log_loss(y_true , y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i , epsilon) for i in y_predicted]
  y_predicted_new = [min(i , 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [36]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [41]:
def gradient_descent(age , bought_insurance , y_true , epochs , loss_thresold):
  w1 = w2 = 1
  bias = 0
  rate = 0.5
  n = len(age)

  for i in range(epochs):
    weighted_sum = w1 * age + w2 * bought_insurance + bias
    y_predicted = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true , y_predicted)
    (y_predicted - y_true)

    w1d = (1/n)*np.dot(np.transpose(age) , (y_predicted - y_true))
    w2d = (1/n)*np.dot(np.transpose(bought_insurance) , (y_predicted - y_true))

    bias_d = np.mean(y_predicted - y_true)
    w1 = w1 - rate * w1d
    w2 = w2 - rate * w2d
    bias = bias - rate * bias_d

    print(f'Epochs : {i} , w1 : {w1} , w2 : {w2} , bias : {bias} , loss : {loss}')
    if loss <= loss_thresold:
      break


  return w1 , w2 , bias

In [42]:
gradient_descent(X_train_scaled['age'] , X_train_scaled['bought_insurance'] , y_train , 1000 , 0.4631)

Epochs : 0 , w1 : 0.9830154083972941 , w2 : 1.047872876722463 , bias : -0.08829665675143072 , loss : 0.5111333285771688
Epochs : 1 , w1 : 0.9685818164768616 , w2 : 1.0976820861278855 , bias : -0.1692122859195178 , loss : 0.49098103777869134
Epochs : 2 , w1 : 0.9563894289460875 , w2 : 1.1490496779554256 , bias : -0.2435540954354597 , loss : 0.4729937190123176
Epochs : 3 , w1 : 0.9461477401258335 , w2 : 1.2016236301698378 , bias : -0.3120777217781943 , loss : 0.45675980409470335


(0.9461477401258335, 1.2016236301698378, -0.3120777217781943)

In [40]:
coef, intercept

(array([[0.6241079],
        [1.5113713]], dtype=float32),
 array([-0.44095188], dtype=float32))